/* Minimal FreeRTOSConfig.h for standalone CMake builds.
 * When building inside IDF (idf.py), this file is generated by the Kconfig system.
 */
#ifndef FREERTOS_CONFIG_H
#define FREERTOS_CONFIG_H

#define configUSE_PREEMPTION            1
#define configUSE_IDLE_HOOK             0
#define configUSE_TICK_HOOK             0
#define configCPU_CLOCK_HZ              ((unsigned long)240000000)
#define configTICK_RATE_HZ              ((TickType_t)100)
#define configMAX_TASK_NAME_LEN         (16)
#define configTASK_NOTIFICATION_ARRAY_ENTRIES 1
#define configMINIMAL_STACK_SIZE        ((unsigned short)768)
#define configSTACK_DEPTH_TYPE          uint32_t
#define configMESSAGE_BUFFER_LENGTH_TYPE size_t

#endif /* FREERTOS_CONFIG_H */
