/* Minimal FreeRTOSConfig.h for standalone CMake builds.
 * When building inside IDF (idf.py), this file is generated by the Kconfig system.
 *
 * 仅用于宿主（非 IDF）CMake 构建：让 #include "freertos/FreeRTOS.h" 可解析。
 * IDF 构建下真实配置由 Kconfig 生成，本文件绝不能出现在组件的导出 include
 * 路径上——否则会遮蔽 IDF 的真配置（tick 100 vs 工程 1000），而且这里的
 * configTICK_RATE_HZ 引用了 TickType_t，在 IDF 的编译单元里根本编不过。
 * 交叉示例的 eui_idf_config_asserts.c 守着这条不变式。
 */
#ifndef FREERTOS_CONFIG_H
#define FREERTOS_CONFIG_H

#define configUSE_PREEMPTION            1
#define configUSE_IDLE_HOOK             0
#define configUSE_TICK_HOOK             0
#define configCPU_CLOCK_HZ              ((unsigned long)240000000)
#define configTICK_RATE_HZ              ((TickType_t)100)
#define configMAX_TASK_NAME_LEN         (16)
#define configTASK_NOTIFICATION_ARRAY_ENTRIES 1
#define configMINIMAL_STACK_SIZE        ((unsigned short)768)
#define configSTACK_DEPTH_TYPE          uint32_t
#define configMESSAGE_BUFFER_LENGTH_TYPE size_t

#endif /* FREERTOS_CONFIG_H */
