# tools/config_to_header.cmake
# Generates eui_profile_config.h from CMake variables set by config profile.
# Called with -DVAR1=value1 -DVAR2=value2 ... -DCONFIG_VARS="VAR1 VAR2 ..." -DOUTPUT_HEADER=<path> -P ...
# All variables listed in CONFIG_VARS are also passed as -D args.
# CONFIG_VARS may be space- or semicolon-separated.

if(NOT DEFINED CONFIG_VARS OR NOT DEFINED OUTPUT_HEADER)
    message(FATAL_ERROR "Usage: cmake -DVAR=value ... -DCONFIG_VARS=... -DOUTPUT_HEADER=... -P tools/config_to_header.cmake")
endif()

# Normalise separators: space and semicolon both become semicolon
string(REPLACE " " ";" _vars "${CONFIG_VARS}")

set(output "/* Auto-generated by tools/config_to_header.cmake — DO NOT EDIT */\n")
set(have_any FALSE)

foreach(var_name ${_vars})
    if(DEFINED ${var_name})
        set(val "${${var_name}}")
        if(val STREQUAL "")
            continue()
        endif()
        if(NOT have_any)
            set(have_any TRUE)
            string(APPEND output "#ifndef EUI_PROFILE_CONFIG_H\n#define EUI_PROFILE_CONFIG_H\n\n")
        endif()
        if(val MATCHES "^[0-9]+$" OR val MATCHES "^0x[0-9a-fA-F]+$")
            string(APPEND output "#define ${var_name} ${val}\n")
        else()
            string(APPEND output "#define ${var_name} \"${val}\"\n")
        endif()
    endif()
endforeach()

if(have_any)
    string(APPEND output "\n#endif /* EUI_PROFILE_CONFIG_H */\n")
endif()

file(WRITE "${OUTPUT_HEADER}" "${output}")
message(STATUS "Generated ${OUTPUT_HEADER}")
