#!/usr/bin/env python3
"""Generate a test VLW font for unit testing.
Format: Processing .vlw binary, all ints big-endian.
8 glyphs (A-H), 8x8 each, at 12px size.
"""
import struct

def be32(v):
    return struct.pack('>i', v)

def bdf_row_to_8bpp(byte, width=8):
    """Convert 1bpp BDF row byte to 8 8bpp bytes. 1=ink(0), 0=bg(255)"""
    return bytes(0 if (byte >> (7-i)) & 1 else 255 for i in range(width))

# BDF glyph bitmaps (8x8) for chars A-H, matching eui_font_builtin.c
bdf_glyphs = {
    'A': [0x18, 0x3C, 0x66, 0x7E, 0x66, 0x66, 0x66, 0x00],
    'B': [0x7C, 0x66, 0x66, 0x7C, 0x66, 0x66, 0x7C, 0x00],
    'C': [0x3C, 0x66, 0x60, 0x60, 0x60, 0x66, 0x3C, 0x00],
    'D': [0x78, 0x6C, 0x66, 0x66, 0x66, 0x6C, 0x78, 0x00],
    'E': [0x7E, 0x60, 0x60, 0x7C, 0x60, 0x60, 0x7E, 0x00],
    'F': [0x7E, 0x60, 0x60, 0x7C, 0x60, 0x60, 0x60, 0x00],
    'G': [0x3C, 0x66, 0x60, 0x6E, 0x66, 0x66, 0x3C, 0x00],
    'H': [0x66, 0x66, 0x66, 0x7E, 0x66, 0x66, 0x66, 0x00],
}

glyph_count = 8
version = 11
font_size = 12
ascent = 10
descent = 2
glyph_w = 8
glyph_h = 8
set_width = 8

data = bytearray()

# Header (24 bytes)
data += be32(glyph_count)   # [0-3]
data += be32(version)       # [4-7]
data += be32(font_size)     # [8-11]
data += be32(0)             # [12-15] mboxY (ignored)
data += be32(ascent)        # [16-19]
data += be32(descent)       # [20-23]

# Glyph headers (28 bytes each, sorted A-H)
for ch in sorted(bdf_glyphs.keys()):
    data += be32(ord(ch))   # [0-3]  value (Unicode code point)
    data += be32(glyph_h)   # [4-7]  height
    data += be32(glyph_w)   # [8-11] width
    data += be32(set_width) # [12-15] setWidth
    data += be32(8)         # [16-19] topExtent
    data += be32(0)         # [20-23] leftExtent
    data += be32(0)         # [24-27] padding

# Glyph bitmaps (width * height bytes each, sequential)
for ch in sorted(bdf_glyphs.keys()):
    rows = bdf_glyphs[ch]
    for row in rows:
        data += bdf_row_to_8bpp(row, 8)

# Convert to C array
hex_bytes = ', '.join(f'0x{b:02X}' for b in data)

print(f'''/* Auto-generated test VLW font (Processing .vlw format)
 * 8 glyphs A-H, 8x8 pixels, 8bpp grayscale.
 * Generated by tools/gen_test_vlw.py
 */
#ifndef TEST_VLW_FONT_H
#define TEST_VLW_FONT_H

#include <stdint.h>

#define TEST_VLW_GLYPH_COUNT {glyph_count}
#define TEST_VLW_ASCENT {ascent}
#define TEST_VLW_DESCENT {descent}
#define TEST_VLW_SIZE {font_size}

static const uint8_t test_vlw_font_data[] = {{
    {hex_bytes}
}};

#endif /* TEST_VLW_FONT_H */
''')
