#!/usr/bin/env python3
"""Generate a test u8g2-format font with 8 glyphs (A-H), 8x8 pixels, 1bpp.
Format: real u8g2 binary format with index table entries.
"""
import struct

GLYPH_COUNT = 8
BITS_PER_0 = 4
BITS_PER_1 = 4
BITS_PER_CHAR_W = 4
BITS_PER_CHAR_H = 4
BITS_PER_CHAR_X = 4
BITS_PER_CHAR_Y = 4
BITS_PER_DELTA_X = 4
MAX_CHAR_W = 8
MAX_CHAR_H = 8

bdf_glyphs = {
    'A': [0x18, 0x3C, 0x66, 0x7E, 0x66, 0x66, 0x66, 0x00],
    'B': [0x7C, 0x66, 0x66, 0x7C, 0x66, 0x66, 0x7C, 0x00],
    'C': [0x3C, 0x66, 0x60, 0x60, 0x60, 0x66, 0x3C, 0x00],
    'D': [0x78, 0x6C, 0x66, 0x66, 0x66, 0x6C, 0x78, 0x00],
    'E': [0x7E, 0x60, 0x60, 0x7C, 0x60, 0x60, 0x7E, 0x00],
    'F': [0x7E, 0x60, 0x60, 0x7C, 0x60, 0x60, 0x60, 0x00],
    'G': [0x3C, 0x66, 0x60, 0x6E, 0x66, 0x66, 0x3C, 0x00],
    'H': [0x66, 0x66, 0x66, 0x7E, 0x66, 0x66, 0x66, 0x00],
}

class BitWriter:
    def __init__(self):
        self.bytes = bytearray()
        self.current_byte = 0
        self.bit_pos = 7

    def write_bits(self, value, num_bits):
        for i in range(num_bits - 1, -1, -1):
            bit = (value >> i) & 1
            self.current_byte |= (bit << self.bit_pos)
            self.bit_pos -= 1
            if self.bit_pos < 0:
                self.bytes.append(self.current_byte)
                self.current_byte = 0
                self.bit_pos = 7

    def flush(self):
        if self.bit_pos < 7:
            self.bytes.append(self.current_byte)
            self.current_byte = 0
            self.bit_pos = 7

    def get_data(self):
        self.flush()
        return bytes(self.bytes)

# Build font data
data = bytearray()

# 23-byte header (real u8g2 format)
data.append(GLYPH_COUNT)               # 0: glyph_cnt
data.append(0)                          # 1: bbx_mode
data.append(BITS_PER_0)                # 2
data.append(BITS_PER_1)                # 3
data.append(BITS_PER_CHAR_W)           # 4
data.append(BITS_PER_CHAR_H)           # 5
data.append(BITS_PER_CHAR_X)           # 6
data.append(BITS_PER_CHAR_Y)           # 7
data.append(BITS_PER_DELTA_X)          # 8
data.append(MAX_CHAR_W)                # 9: max_char_width
data.append(MAX_CHAR_H)                # 10: max_char_height
data.append(0)                          # 11: x_offset
data.append(0)                          # 12: y_offset
data.append(8)                          # 13: ascent_A
data.append(0)                          # 14: descent_g
data.append(10)                         # 15: ascent_para
data.append(0)                          # 16: descent_para
data += struct.pack('>H', 0)           # 17-18: start_pos_upper_A (BE)
data += struct.pack('>H', 0)           # 19-20: start_pos_lower_a (BE)
data += struct.pack('>H', 0)           # 21-22: start_pos_unicode (BE)

MAX_RUN = (1 << BITS_PER_0) - 1        # all-1s = continue

for ch in sorted(bdf_glyphs.keys()):
    glyph_rows = bdf_glyphs[ch]

    bw = BitWriter()

    bw.write_bits(MAX_CHAR_W, BITS_PER_CHAR_W)
    bw.write_bits(MAX_CHAR_H, BITS_PER_CHAR_H)
    bw.write_bits(0, BITS_PER_CHAR_X)
    bw.write_bits(0, BITS_PER_CHAR_Y)
    bw.write_bits(MAX_CHAR_W, BITS_PER_DELTA_X)

    run_type = 0
    run_length = 0
    max_run = MAX_RUN - 1

    for row in glyph_rows:
        for col in range(8):
            bit = (row >> (7 - col)) & 1
            if bit == run_type:
                run_length += 1
            else:
                while run_length >= max_run:
                    bw.write_bits(max_run, BITS_PER_0 if run_type == 0 else BITS_PER_1)
                    run_length -= max_run
                bw.write_bits(run_length, BITS_PER_0 if run_type == 0 else BITS_PER_1)
                run_type = bit
                run_length = 1
    while run_length >= max_run:
        bw.write_bits(max_run, BITS_PER_0 if run_type == 0 else BITS_PER_1)
        run_length -= max_run
    bw.write_bits(run_length, BITS_PER_0 if run_type == 0 else BITS_PER_1)

    packed = bw.get_data()
    total_size = 2 + len(packed)

    data.append(ord(ch))
    data.append(total_size)
    data += packed

data.append(0)
data.append(0)

# Compute section offsets from byte 23 for uppercase/lowercase sections
pos = 23
idx = 0
while True:
    enc = data[pos]
    sz = data[pos + 1]
    if sz == 0:
        break
    if idx == ord('A') - 32:
        struct.pack_into('>H', data, 17, pos - 23)
    if idx == ord('a') - 32:
        struct.pack_into('>H', data, 19, pos - 23)
    pos += sz
    idx += 1

hex_lines = []
for i in range(0, len(data), 16):
    chunk = data[i:i+16]
    hex_str = ', '.join(f'0x{b:02X}' for b in chunk)
    hex_lines.append(f'    {hex_str}')

with open('test/test_u8g2_font.h', 'w') as f:
    f.write(f'''/* Auto-generated test u8g2 format font
 * {GLYPH_COUNT} glyphs A-H, 8x8 pixels, 1bpp, fixed-width
 * Generated by tools/gen_test_u8g2_font.py
 */
#ifndef TEST_U8G2_FONT_H
#define TEST_U8G2_FONT_H

#include <stdint.h>

#define TEST_U8G2_GLYPH_COUNT {GLYPH_COUNT}
#define TEST_U8G2_FONT_HEIGHT {MAX_CHAR_H}
#define TEST_U8G2_FONT_BASELINE 7

static const uint8_t test_u8g2_font_data[] = {{
{','.join(hex_lines)}
}};

#endif /* TEST_U8G2_FONT_H */
''')
print("Generated test/test_u8g2_font.h")
