#!/usr/bin/env python3
"""Generate a u8g2-format test font with kerning encoding table.
4 glyphs: regular T(0), regular A(1), kerning T(2), kerning A(3).
"""
import struct

GLYPH_CNT = 4
BITS_PER_0 = 4
BITS_PER_1 = 4
BITS_PER_CHAR_W = 4
BITS_PER_CHAR_H = 4
BITS_PER_CHAR_X = 4
BITS_PER_CHAR_Y = 4
BITS_PER_DELTA_X = 4
MAX_CHAR_W = 8
MAX_CHAR_H = 8

glyphs = [
    [0xFE, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x00],
    [0x18, 0x24, 0x42, 0x7E, 0x42, 0x42, 0x42, 0x00],
    [0xFE, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x00],
    [0x18, 0x24, 0x42, 0x7E, 0x42, 0x42, 0x42, 0x00],
]
advances = [8, 8, 6, 8]

class BitWriter:
    def __init__(self):
        self.bytes = bytearray()
        self.current_byte = 0
        self.bit_pos = 7

    def write_bits(self, value, num_bits):
        for i in range(num_bits - 1, -1, -1):
            bit = (value >> i) & 1
            self.current_byte |= (bit << self.bit_pos)
            self.bit_pos -= 1
            if self.bit_pos < 0:
                self.bytes.append(self.current_byte)
                self.current_byte = 0
                self.bit_pos = 7

    def flush(self):
        if self.bit_pos < 7:
            self.bytes.append(self.current_byte)
            self.current_byte = 0
            self.bit_pos = 7

    def get_data(self):
        self.flush()
        return bytes(self.bytes)

data = bytearray()

# 23-byte header
data.append(GLYPH_CNT)
data.append(0)
data.append(BITS_PER_0)
data.append(BITS_PER_1)
data.append(BITS_PER_CHAR_W)
data.append(BITS_PER_CHAR_H)
data.append(BITS_PER_CHAR_X)
data.append(BITS_PER_CHAR_Y)
data.append(BITS_PER_DELTA_X)
data.append(MAX_CHAR_W)
data.append(MAX_CHAR_H)
data.append(0)
data.append(0)
data.append(8)
data.append(0)
data.append(10)
data.append(0)
data += struct.pack('>H', 0)           # 17-18: start_pos_upper_A (BE)
data += struct.pack('>H', 0)           # 19-20: start_pos_lower_a (BE)
data += struct.pack('>H', 0)           # 21-22: start_pos_unicode (BE)

MAX_RUN = (1 << BITS_PER_0) - 1
max_run = MAX_RUN - 1

for i, g in enumerate(glyphs):
    bw = BitWriter()
    bw.write_bits(MAX_CHAR_W, BITS_PER_CHAR_W)
    bw.write_bits(MAX_CHAR_H, BITS_PER_CHAR_H)
    bw.write_bits(0, BITS_PER_CHAR_X)
    bw.write_bits(0, BITS_PER_CHAR_Y)
    bw.write_bits(advances[i], BITS_PER_DELTA_X)

    run_type = 0
    run_length = 0
    for row in g:
        for col in range(8):
            bit = (row >> (7 - col)) & 1
            if bit == run_type:
                run_length += 1
            else:
                while run_length >= max_run:
                    bw.write_bits(max_run, BITS_PER_0 if run_type == 0 else BITS_PER_1)
                    run_length -= max_run
                bw.write_bits(run_length, BITS_PER_0 if run_type == 0 else BITS_PER_1)
                run_type = bit
                run_length = 1
    while run_length >= max_run:
        bw.write_bits(max_run, BITS_PER_0 if run_type == 0 else BITS_PER_1)
        run_length -= max_run
    bw.write_bits(run_length, BITS_PER_0 if run_type == 0 else BITS_PER_1)

    packed = bw.get_data()
    total_size = 2 + len(packed)

    if i == 0:
        data.append(ord('T'))
    elif i == 1:
        data.append(ord('A'))
    else:
        data.append(i)
    data.append(total_size)
    data += packed

data.append(0)
data.append(0)

enc = bytearray()
enc.append(1)
enc += struct.pack('<H', 4)
enc += struct.pack('<H', ord('T')) + bytes([0])
enc += struct.pack('<H', ord('A')) + bytes([1])
enc += struct.pack('<H', (ord('T') << 8) | ord('A')) + bytes([2])
enc += struct.pack('<H', (ord('T') << 8) | ord('A')) + bytes([3])
data += enc

# Compute section offsets from byte 23
unicode_offset = len(data) - len(enc) - 23
struct.pack_into('>H', data, 21, unicode_offset)

pos = 23
idx = 0
while True:
    enc_byte = data[pos]
    sz = data[pos + 1]
    if sz == 0:
        break
    if idx == ord('A') - 32:
        struct.pack_into('>H', data, 17, pos - 23)
    if idx == ord('a') - 32:
        struct.pack_into('>H', data, 19, pos - 23)
    pos += sz
    idx += 1

hex_lines = []
for i in range(0, len(data), 16):
    chunk = data[i:i+16]
    hex_lines.append('    ' + ', '.join(f'0x{b:02X}' for b in chunk))

with open('test/test_font_kerning.h', 'w') as f:
    f.write(f'''/* Auto-generated u8g2 kerning test font
 * {GLYPH_CNT} glyphs (T, A, T_kern, A_kern) with encoding table.
 * Generated by tools/gen_test_u8g2_kerning.py
 */
#ifndef TEST_FONT_KERNING_H
#define TEST_FONT_KERNING_H

#include <stdint.h>

static const uint8_t test_kern_font_data[] = {{
{','.join(hex_lines)}
}};

#endif
''')
print("Generated test/test_font_kerning.h")
